language: java
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "git clone https://github.com/geomajas/geomajas-build-tools target/geomajas-build-tools"
jdk:
  - oraclejdk7
cache:
  directories:
  - $HOME/.m2
install: mvn verify -B -V -q -Dgwt.compiler.localWorkers=2 -DskipTests=true --settings target/geomajas-build-tools/settings.xml
script: mvn test -B -V -q --settings target/geomajas-build-tools/settings.xml
env: MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=2g"
