language: java
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "git clone https://github.com/geomajas/geomajas-build-tools target/geomajas-build-tools"
jdk:
  - oraclejdk7
cache:
  directories:
  - $HOME/.m2
install: mvn verify -B -V -Dgwt.compiler.localWorkers=2 -DskipTests=true --settings target/geomajas-build-tools/settings.xml | grep -v Download.*http
script: mvn test -B -V --settings target/geomajas-build-tools/settings.xml
env: MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=1024m"
