language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "git clone https://github.com/geomajas/geomajas-build-tools target/geomajas-build-tools"
jdk:
  - oraclejdk7
cache:
  directories:
  - $HOME/.m2
install: true
script: "travis_retry mvn verify -B -V --settings target/geomajas-build-tools/settings.xml"
env: MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=512m"
